# Generated by Django 4.0 on 2023-08-14 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('8d150256-2e02-43d1-97a9-12cef0e8c873'), editable=False, unique=True),
        ),
    ]
